# Generated by Django 4.2.9 on 2024-01-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team',
            new_name='offer',
        ),
    ]
